// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Context;

#nullable disable

namespace APIApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230705102840_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("APIApp.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPlayerWin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player1id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player2id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Game");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("APIApp.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Player");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Player");
                });

            modelBuilder.Entity("APIApp.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Score");

                    b.ToTable("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
